name: JaBa
description: "JaBa — marketplace de seconde main entre particuliers, Sénégal."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.3   # persistance locale (comptes, catalogue, messages)
  crypto: ^3.0.5               # hachage des mots de passe stockés localement
  image_picker: ^1.2.3         # vraie galerie / appareil photo
  path_provider: ^2.1.6        # copie permanente des photos importées
  url_launcher: ^6.3.2         # ouverture de WhatsApp depuis le chat
  font_awesome_flutter: ^11.0.0
  # go_router: ^14.0.0
  # firebase_core: ^3.0.0
  # firebase_auth: ^5.0.0
  # cloud_firestore: ^5.0.0
  # firebase_storage: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
